services:
  - type: web
    name: bcb-mobile-bankin
    runtime: static
    rootDir: .
    buildCommand: corepack enable && corepack pnpm install --frozen-lockfile && corepack pnpm --dir src/frontend build
    staticPublishPath: src/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
