/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Amount = IDL.Nat;
export const LoanApplicationRequest = IDL.Record({
  'loanType' : IDL.Text,
  'termMonths' : IDL.Nat,
  'amountPesewas' : Amount,
  'purpose' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const RepaymentScheduleEntry = IDL.Record({
  'dueDate' : Timestamp,
  'isPaid' : IDL.Bool,
  'amountPesewas' : Amount,
  'paidAt' : IDL.Opt(Timestamp),
});
export const LoanInfo = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'appliedAt' : Timestamp,
  'approvedAt' : IDL.Opt(Timestamp),
  'interestRateBps' : IDL.Nat,
  'repaymentSchedule' : IDL.Vec(RepaymentScheduleEntry),
  'loanType' : IDL.Text,
  'termMonths' : IDL.Nat,
  'principalPesewas' : Amount,
  'disbursedAt' : IDL.Opt(Timestamp),
});
export const LoanError = IDL.Variant({
  'loanNotFound' : IDL.Null,
  'alreadyApplied' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidAmount' : IDL.Null,
});
export const AuthError = IDL.Variant({
  'phoneAlreadyExists' : IDL.Null,
  'userNotFound' : IDL.Null,
  'invalidPin' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const CardError = IDL.Variant({
  'invalidLimit' : IDL.Null,
  'alreadyFrozen' : IDL.Null,
  'alreadyActive' : IDL.Null,
  'cardNotFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const AccountInfo = IDL.Record({
  'id' : IDL.Text,
  'balancePesewas' : Amount,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'accountType' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const CardInfo = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'cardNetwork' : IDL.Text,
  'expiryMonth' : IDL.Nat,
  'createdAt' : Timestamp,
  'expiryYear' : IDL.Nat,
  'maskedPan' : IDL.Text,
  'dailyLimitPesewas' : Amount,
  'cardholderName' : IDL.Text,
  'monthlyLimitPesewas' : Amount,
});
export const NotificationRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'kycStatus' : IDL.Text,
  'phone' : IDL.Text,
  'ghanaCard' : IDL.Text,
});
export const TransactionRecord = IDL.Record({
  'id' : IDL.Text,
  'counterpartyAccount' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : Timestamp,
  'reference' : IDL.Text,
  'description' : IDL.Text,
  'counterpartyName' : IDL.Text,
  'amountPesewas' : Amount,
  'category' : IDL.Text,
  'txType' : IDL.Text,
});
export const LoginRequest = IDL.Record({
  'pin' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentRequest = IDL.Record({
  'meterOrSmartCard' : IDL.Text,
  'description' : IDL.Text,
  'amountPesewas' : Amount,
  'paymentType' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const TransactionError = IDL.Variant({
  'transferFailed' : IDL.Null,
  'insufficientFunds' : IDL.Null,
  'accountNotFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'invalidAmount' : IDL.Null,
});
export const NotificationError = IDL.Variant({
  'notificationNotFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const RegisterRequest = IDL.Record({
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'ghanaCard' : IDL.Text,
});
export const TransferRequest = IDL.Record({
  'transferType' : IDL.Text,
  'network' : IDL.Text,
  'description' : IDL.Text,
  'fromAccountNumber' : IDL.Text,
  'bankCode' : IDL.Text,
  'amountPesewas' : Amount,
  'toAccountNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'applyForLoan' : IDL.Func(
      [LoanApplicationRequest],
      [IDL.Variant({ 'ok' : LoanInfo, 'err' : LoanError })],
      [],
    ),
  'changePin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'freezeCard' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
      [],
    ),
  'getAccount' : IDL.Func([IDL.Text], [IDL.Opt(AccountInfo)], ['query']),
  'getCard' : IDL.Func([IDL.Text], [IDL.Opt(CardInfo)], ['query']),
  'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(LoanInfo)], ['query']),
  'getMyAccounts' : IDL.Func([], [IDL.Vec(AccountInfo)], ['query']),
  'getMyCards' : IDL.Func([], [IDL.Vec(CardInfo)], ['query']),
  'getMyLoans' : IDL.Func([], [IDL.Vec(LoanInfo)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(NotificationRecord)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(TransactionRecord)], ['query']),
  'getTransaction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TransactionRecord)],
      ['query'],
    ),
  'login' : IDL.Func(
      [LoginRequest],
      [IDL.Variant({ 'ok' : UserProfile, 'err' : AuthError })],
      [],
    ),
  'makePayment' : IDL.Func(
      [PaymentRequest],
      [IDL.Variant({ 'ok' : TransactionRecord, 'err' : TransactionError })],
      [],
    ),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : NotificationError })],
      [],
    ),
  'register' : IDL.Func(
      [RegisterRequest],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
  'requestCard' : IDL.Func([IDL.Text], [CardInfo], []),
  'setSpendingLimits' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
      [],
    ),
  'transfer' : IDL.Func(
      [TransferRequest],
      [IDL.Variant({ 'ok' : TransactionRecord, 'err' : TransactionError })],
      [],
    ),
  'unfreezeCard' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Amount = IDL.Nat;
  const LoanApplicationRequest = IDL.Record({
    'loanType' : IDL.Text,
    'termMonths' : IDL.Nat,
    'amountPesewas' : Amount,
    'purpose' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const RepaymentScheduleEntry = IDL.Record({
    'dueDate' : Timestamp,
    'isPaid' : IDL.Bool,
    'amountPesewas' : Amount,
    'paidAt' : IDL.Opt(Timestamp),
  });
  const LoanInfo = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'appliedAt' : Timestamp,
    'approvedAt' : IDL.Opt(Timestamp),
    'interestRateBps' : IDL.Nat,
    'repaymentSchedule' : IDL.Vec(RepaymentScheduleEntry),
    'loanType' : IDL.Text,
    'termMonths' : IDL.Nat,
    'principalPesewas' : Amount,
    'disbursedAt' : IDL.Opt(Timestamp),
  });
  const LoanError = IDL.Variant({
    'loanNotFound' : IDL.Null,
    'alreadyApplied' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidAmount' : IDL.Null,
  });
  const AuthError = IDL.Variant({
    'phoneAlreadyExists' : IDL.Null,
    'userNotFound' : IDL.Null,
    'invalidPin' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const CardError = IDL.Variant({
    'invalidLimit' : IDL.Null,
    'alreadyFrozen' : IDL.Null,
    'alreadyActive' : IDL.Null,
    'cardNotFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const AccountInfo = IDL.Record({
    'id' : IDL.Text,
    'balancePesewas' : Amount,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'accountType' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const CardInfo = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'cardNetwork' : IDL.Text,
    'expiryMonth' : IDL.Nat,
    'createdAt' : Timestamp,
    'expiryYear' : IDL.Nat,
    'maskedPan' : IDL.Text,
    'dailyLimitPesewas' : Amount,
    'cardholderName' : IDL.Text,
    'monthlyLimitPesewas' : Amount,
  });
  const NotificationRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'kycStatus' : IDL.Text,
    'phone' : IDL.Text,
    'ghanaCard' : IDL.Text,
  });
  const TransactionRecord = IDL.Record({
    'id' : IDL.Text,
    'counterpartyAccount' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : Timestamp,
    'reference' : IDL.Text,
    'description' : IDL.Text,
    'counterpartyName' : IDL.Text,
    'amountPesewas' : Amount,
    'category' : IDL.Text,
    'txType' : IDL.Text,
  });
  const LoginRequest = IDL.Record({ 'pin' : IDL.Text, 'phone' : IDL.Text });
  const PaymentRequest = IDL.Record({
    'meterOrSmartCard' : IDL.Text,
    'description' : IDL.Text,
    'amountPesewas' : Amount,
    'paymentType' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const TransactionError = IDL.Variant({
    'transferFailed' : IDL.Null,
    'insufficientFunds' : IDL.Null,
    'accountNotFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'invalidAmount' : IDL.Null,
  });
  const NotificationError = IDL.Variant({
    'notificationNotFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const RegisterRequest = IDL.Record({
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'ghanaCard' : IDL.Text,
  });
  const TransferRequest = IDL.Record({
    'transferType' : IDL.Text,
    'network' : IDL.Text,
    'description' : IDL.Text,
    'fromAccountNumber' : IDL.Text,
    'bankCode' : IDL.Text,
    'amountPesewas' : Amount,
    'toAccountNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'applyForLoan' : IDL.Func(
        [LoanApplicationRequest],
        [IDL.Variant({ 'ok' : LoanInfo, 'err' : LoanError })],
        [],
      ),
    'changePin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'freezeCard' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
        [],
      ),
    'getAccount' : IDL.Func([IDL.Text], [IDL.Opt(AccountInfo)], ['query']),
    'getCard' : IDL.Func([IDL.Text], [IDL.Opt(CardInfo)], ['query']),
    'getLoan' : IDL.Func([IDL.Text], [IDL.Opt(LoanInfo)], ['query']),
    'getMyAccounts' : IDL.Func([], [IDL.Vec(AccountInfo)], ['query']),
    'getMyCards' : IDL.Func([], [IDL.Vec(CardInfo)], ['query']),
    'getMyLoans' : IDL.Func([], [IDL.Vec(LoanInfo)], ['query']),
    'getMyNotifications' : IDL.Func(
        [],
        [IDL.Vec(NotificationRecord)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], []),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(TransactionRecord)], ['query']),
    'getTransaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TransactionRecord)],
        ['query'],
      ),
    'login' : IDL.Func(
        [LoginRequest],
        [IDL.Variant({ 'ok' : UserProfile, 'err' : AuthError })],
        [],
      ),
    'makePayment' : IDL.Func(
        [PaymentRequest],
        [IDL.Variant({ 'ok' : TransactionRecord, 'err' : TransactionError })],
        [],
      ),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : NotificationError })],
        [],
      ),
    'register' : IDL.Func(
        [RegisterRequest],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
    'requestCard' : IDL.Func([IDL.Text], [CardInfo], []),
    'setSpendingLimits' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
        [],
      ),
    'transfer' : IDL.Func(
        [TransferRequest],
        [IDL.Variant({ 'ok' : TransactionRecord, 'err' : TransactionError })],
        [],
      ),
    'unfreezeCard' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : CardError })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AuthError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };