/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountInfo {
  'id' : string,
  'balancePesewas' : Amount,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'accountType' : string,
  'accountNumber' : string,
}
export type Amount = bigint;
export type AuthError = { 'phoneAlreadyExists' : null } |
  { 'userNotFound' : null } |
  { 'invalidPin' : null } |
  { 'unauthorized' : null };
export type CardError = { 'invalidLimit' : null } |
  { 'alreadyFrozen' : null } |
  { 'alreadyActive' : null } |
  { 'cardNotFound' : null } |
  { 'unauthorized' : null };
export interface CardInfo {
  'id' : string,
  'status' : string,
  'cardNetwork' : string,
  'expiryMonth' : bigint,
  'createdAt' : Timestamp,
  'expiryYear' : bigint,
  'maskedPan' : string,
  'dailyLimitPesewas' : Amount,
  'cardholderName' : string,
  'monthlyLimitPesewas' : Amount,
}
export interface LoanApplicationRequest {
  'loanType' : string,
  'termMonths' : bigint,
  'amountPesewas' : Amount,
  'purpose' : string,
}
export type LoanError = { 'loanNotFound' : null } |
  { 'alreadyApplied' : null } |
  { 'unauthorized' : null } |
  { 'invalidAmount' : null };
export interface LoanInfo {
  'id' : string,
  'status' : string,
  'appliedAt' : Timestamp,
  'approvedAt' : [] | [Timestamp],
  'interestRateBps' : bigint,
  'repaymentSchedule' : Array<RepaymentScheduleEntry>,
  'loanType' : string,
  'termMonths' : bigint,
  'principalPesewas' : Amount,
  'disbursedAt' : [] | [Timestamp],
}
export interface LoginRequest { 'pin' : string, 'phone' : string }
export type NotificationError = { 'notificationNotFound' : null } |
  { 'unauthorized' : null };
export interface NotificationRecord {
  'id' : string,
  'title' : string,
  'notifType' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'isRead' : boolean,
}
export interface PaymentRequest {
  'meterOrSmartCard' : string,
  'description' : string,
  'amountPesewas' : Amount,
  'paymentType' : string,
  'accountNumber' : string,
}
export interface RegisterRequest {
  'pin' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'ghanaCard' : string,
}
export interface RepaymentScheduleEntry {
  'dueDate' : Timestamp,
  'isPaid' : boolean,
  'amountPesewas' : Amount,
  'paidAt' : [] | [Timestamp],
}
export type Timestamp = bigint;
export type TransactionError = { 'transferFailed' : null } |
  { 'insufficientFunds' : null } |
  { 'accountNotFound' : null } |
  { 'unauthorized' : null } |
  { 'invalidAmount' : null };
export interface TransactionRecord {
  'id' : string,
  'counterpartyAccount' : string,
  'status' : string,
  'createdAt' : Timestamp,
  'reference' : string,
  'description' : string,
  'counterpartyName' : string,
  'amountPesewas' : Amount,
  'category' : string,
  'txType' : string,
}
export interface TransferRequest {
  'transferType' : string,
  'network' : string,
  'description' : string,
  'fromAccountNumber' : string,
  'bankCode' : string,
  'amountPesewas' : Amount,
  'toAccountNumber' : string,
}
export interface UserProfile {
  'id' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'kycStatus' : string,
  'phone' : string,
  'ghanaCard' : string,
}
export interface _SERVICE {
  'applyForLoan' : ActorMethod<
    [LoanApplicationRequest],
    { 'ok' : LoanInfo } |
      { 'err' : LoanError }
  >,
  'changePin' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'freezeCard' : ActorMethod<[string], { 'ok' : null } | { 'err' : CardError }>,
  'getAccount' : ActorMethod<[string], [] | [AccountInfo]>,
  'getCard' : ActorMethod<[string], [] | [CardInfo]>,
  'getLoan' : ActorMethod<[string], [] | [LoanInfo]>,
  'getMyAccounts' : ActorMethod<[], Array<AccountInfo>>,
  'getMyCards' : ActorMethod<[], Array<CardInfo>>,
  'getMyLoans' : ActorMethod<[], Array<LoanInfo>>,
  'getMyNotifications' : ActorMethod<[], Array<NotificationRecord>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyTransactions' : ActorMethod<[], Array<TransactionRecord>>,
  'getTransaction' : ActorMethod<[string], [] | [TransactionRecord]>,
  'login' : ActorMethod<
    [LoginRequest],
    { 'ok' : UserProfile } |
      { 'err' : AuthError }
  >,
  'makePayment' : ActorMethod<
    [PaymentRequest],
    { 'ok' : TransactionRecord } |
      { 'err' : TransactionError }
  >,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : NotificationError }
  >,
  'register' : ActorMethod<
    [RegisterRequest],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
  'requestCard' : ActorMethod<[string], CardInfo>,
  'setSpendingLimits' : ActorMethod<
    [string, bigint, bigint],
    { 'ok' : null } |
      { 'err' : CardError }
  >,
  'transfer' : ActorMethod<
    [TransferRequest],
    { 'ok' : TransactionRecord } |
      { 'err' : TransactionError }
  >,
  'unfreezeCard' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : CardError }
  >,
  'updateMyProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : AuthError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];