/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface LoginRequest {
    pin: string;
    phone: string;
}
export interface TransferRequest {
    transferType: string;
    network: string;
    description: string;
    fromAccountNumber: string;
    bankCode: string;
    amountPesewas: Amount;
    toAccountNumber: string;
}
export type Amount = bigint;
export interface TransactionRecord {
    id: string;
    counterpartyAccount: string;
    status: string;
    createdAt: Timestamp;
    reference: string;
    description: string;
    counterpartyName: string;
    amountPesewas: Amount;
    category: string;
    txType: string;
}
export interface NotificationRecord {
    id: string;
    title: string;
    notifType: string;
    body: string;
    createdAt: Timestamp;
    isRead: boolean;
}
export interface CardInfo {
    id: string;
    status: string;
    cardNetwork: string;
    expiryMonth: bigint;
    createdAt: Timestamp;
    expiryYear: bigint;
    maskedPan: string;
    dailyLimitPesewas: Amount;
    cardholderName: string;
    monthlyLimitPesewas: Amount;
}
export interface LoanApplicationRequest {
    loanType: string;
    termMonths: bigint;
    amountPesewas: Amount;
    purpose: string;
}
export interface RegisterRequest {
    pin: string;
    name: string;
    email: string;
    phone: string;
    ghanaCard: string;
}
export interface AccountInfo {
    id: string;
    balancePesewas: Amount;
    createdAt: Timestamp;
    isActive: boolean;
    accountType: string;
    accountNumber: string;
}
export interface PaymentRequest {
    meterOrSmartCard: string;
    description: string;
    amountPesewas: Amount;
    paymentType: string;
    accountNumber: string;
}
export interface LoanInfo {
    id: string;
    status: string;
    appliedAt: Timestamp;
    approvedAt?: Timestamp;
    interestRateBps: bigint;
    repaymentSchedule: Array<RepaymentScheduleEntry>;
    loanType: string;
    termMonths: bigint;
    principalPesewas: Amount;
    disbursedAt?: Timestamp;
}
export interface RepaymentScheduleEntry {
    dueDate: Timestamp;
    isPaid: boolean;
    amountPesewas: Amount;
    paidAt?: Timestamp;
}
export interface UserProfile {
    id: string;
    name: string;
    createdAt: Timestamp;
    email: string;
    kycStatus: string;
    phone: string;
    ghanaCard: string;
}
export enum AuthError {
    phoneAlreadyExists = "phoneAlreadyExists",
    userNotFound = "userNotFound",
    invalidPin = "invalidPin",
    unauthorized = "unauthorized"
}
export enum CardError {
    invalidLimit = "invalidLimit",
    alreadyFrozen = "alreadyFrozen",
    alreadyActive = "alreadyActive",
    cardNotFound = "cardNotFound",
    unauthorized = "unauthorized"
}
export enum LoanError {
    loanNotFound = "loanNotFound",
    alreadyApplied = "alreadyApplied",
    unauthorized = "unauthorized",
    invalidAmount = "invalidAmount"
}
export enum NotificationError {
    notificationNotFound = "notificationNotFound",
    unauthorized = "unauthorized"
}
export enum TransactionError {
    transferFailed = "transferFailed",
    insufficientFunds = "insufficientFunds",
    accountNotFound = "accountNotFound",
    unauthorized = "unauthorized",
    invalidAmount = "invalidAmount"
}
export interface backendInterface {
    applyForLoan(req: LoanApplicationRequest): Promise<{
        __kind__: "ok";
        ok: LoanInfo;
    } | {
        __kind__: "err";
        err: LoanError;
    }>;
    changePin(oldPin: string, newPin: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    freezeCard(cardId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }>;
    getAccount(accountNumber: string): Promise<AccountInfo | null>;
    getCard(cardId: string): Promise<CardInfo | null>;
    getLoan(loanId: string): Promise<LoanInfo | null>;
    getMyAccounts(): Promise<Array<AccountInfo>>;
    getMyCards(): Promise<Array<CardInfo>>;
    getMyLoans(): Promise<Array<LoanInfo>>;
    getMyNotifications(): Promise<Array<NotificationRecord>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyTransactions(): Promise<Array<TransactionRecord>>;
    getTransaction(txId: string): Promise<TransactionRecord | null>;
    login(req: LoginRequest): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    makePayment(req: PaymentRequest): Promise<{
        __kind__: "ok";
        ok: TransactionRecord;
    } | {
        __kind__: "err";
        err: TransactionError;
    }>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notifId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: NotificationError;
    }>;
    register(req: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
    requestCard(networkText: string): Promise<CardInfo>;
    setSpendingLimits(cardId: string, dailyLimitPesewas: bigint, monthlyLimitPesewas: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }>;
    transfer(req: TransferRequest): Promise<{
        __kind__: "ok";
        ok: TransactionRecord;
    } | {
        __kind__: "err";
        err: TransactionError;
    }>;
    unfreezeCard(cardId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }>;
    updateMyProfile(name: string, email: string, ghanaCard: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }>;
}
import type { AccountInfo as _AccountInfo, Amount as _Amount, AuthError as _AuthError, CardError as _CardError, CardInfo as _CardInfo, LoanError as _LoanError, LoanInfo as _LoanInfo, NotificationError as _NotificationError, RepaymentScheduleEntry as _RepaymentScheduleEntry, Timestamp as _Timestamp, TransactionError as _TransactionError, TransactionRecord as _TransactionRecord, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyForLoan(arg0: LoanApplicationRequest): Promise<{
        __kind__: "ok";
        ok: LoanInfo;
    } | {
        __kind__: "err";
        err: LoanError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForLoan(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForLoan(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async changePin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changePin(arg0, arg1);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changePin(arg0, arg1);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async freezeCard(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.freezeCard(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.freezeCard(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccount(arg0: string): Promise<AccountInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccount(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccount(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCard(arg0: string): Promise<CardInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCard(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCard(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLoan(arg0: string): Promise<LoanInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoan(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoan(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAccounts(): Promise<Array<AccountInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAccounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAccounts();
            return result;
        }
    }
    async getMyCards(): Promise<Array<CardInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCards();
            return result;
        }
    }
    async getMyLoans(): Promise<Array<LoanInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLoans();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLoans();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<NotificationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return result;
        }
    }
    async getTransaction(arg0: string): Promise<TransactionRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: LoginRequest): Promise<{
        __kind__: "ok";
        ok: UserProfile;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async makePayment(arg0: PaymentRequest): Promise<{
        __kind__: "ok";
        ok: TransactionRecord;
    } | {
        __kind__: "err";
        err: TransactionError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.makePayment(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makePayment(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: NotificationError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterRequest): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestCard(arg0: string): Promise<CardInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.requestCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestCard(arg0);
            return result;
        }
    }
    async setSpendingLimits(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpendingLimits(arg0, arg1, arg2);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpendingLimits(arg0, arg1, arg2);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async transfer(arg0: TransferRequest): Promise<{
        __kind__: "ok";
        ok: TransactionRecord;
    } | {
        __kind__: "err";
        err: TransactionError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transfer(arg0);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transfer(arg0);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async unfreezeCard(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: CardError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unfreezeCard(arg0);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfreezeCard(arg0);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: AuthError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuthError_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuthError): AuthError {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CardError_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardError): CardError {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_LoanError_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanError): LoanError {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_LoanInfo_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoanInfo): LoanInfo {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationError_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationError): NotificationError {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RepaymentScheduleEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepaymentScheduleEntry): RepaymentScheduleEntry {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionError_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionError): TransactionError {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountInfo]): AccountInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CardInfo]): CardInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LoanInfo]): LoanInfo | null {
    return value.length === 0 ? null : from_candid_LoanInfo_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransactionRecord]): TransactionRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    appliedAt: _Timestamp;
    approvedAt: [] | [_Timestamp];
    interestRateBps: bigint;
    repaymentSchedule: Array<_RepaymentScheduleEntry>;
    loanType: string;
    termMonths: bigint;
    principalPesewas: _Amount;
    disbursedAt: [] | [_Timestamp];
}): {
    id: string;
    status: string;
    appliedAt: Timestamp;
    approvedAt?: Timestamp;
    interestRateBps: bigint;
    repaymentSchedule: Array<RepaymentScheduleEntry>;
    loanType: string;
    termMonths: bigint;
    principalPesewas: Amount;
    disbursedAt?: Timestamp;
} {
    return {
        id: value.id,
        status: value.status,
        appliedAt: value.appliedAt,
        approvedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.approvedAt)),
        interestRateBps: value.interestRateBps,
        repaymentSchedule: from_candid_vec_n5(_uploadFile, _downloadFile, value.repaymentSchedule),
        loanType: value.loanType,
        termMonths: value.termMonths,
        principalPesewas: value.principalPesewas,
        disbursedAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.disbursedAt))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dueDate: _Timestamp;
    isPaid: boolean;
    amountPesewas: _Amount;
    paidAt: [] | [_Timestamp];
}): {
    dueDate: Timestamp;
    isPaid: boolean;
    amountPesewas: Amount;
    paidAt?: Timestamp;
} {
    return {
        dueDate: value.dueDate,
        isPaid: value.isPaid,
        amountPesewas: value.amountPesewas,
        paidAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.paidAt))
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LoanInfo;
} | {
    err: _LoanError;
}): {
    __kind__: "ok";
    ok: LoanInfo;
} | {
    __kind__: "err";
    err: LoanError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LoanInfo_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_LoanError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    phoneAlreadyExists: null;
} | {
    userNotFound: null;
} | {
    invalidPin: null;
} | {
    unauthorized: null;
}): AuthError {
    return "phoneAlreadyExists" in value ? AuthError.phoneAlreadyExists : "userNotFound" in value ? AuthError.userNotFound : "invalidPin" in value ? AuthError.invalidPin : "unauthorized" in value ? AuthError.unauthorized : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _CardError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: CardError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_CardError_n14(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidLimit: null;
} | {
    alreadyFrozen: null;
} | {
    alreadyActive: null;
} | {
    cardNotFound: null;
} | {
    unauthorized: null;
}): CardError {
    return "invalidLimit" in value ? CardError.invalidLimit : "alreadyFrozen" in value ? CardError.alreadyFrozen : "alreadyActive" in value ? CardError.alreadyActive : "cardNotFound" in value ? CardError.cardNotFound : "unauthorized" in value ? CardError.unauthorized : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: _AuthError;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: AuthError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_AuthError_n11(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TransactionRecord;
} | {
    err: _TransactionError;
}): {
    __kind__: "ok";
    ok: TransactionRecord;
} | {
    __kind__: "err";
    err: TransactionError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_TransactionError_n24(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transferFailed: null;
} | {
    insufficientFunds: null;
} | {
    accountNotFound: null;
} | {
    unauthorized: null;
} | {
    invalidAmount: null;
}): TransactionError {
    return "transferFailed" in value ? TransactionError.transferFailed : "insufficientFunds" in value ? TransactionError.insufficientFunds : "accountNotFound" in value ? TransactionError.accountNotFound : "unauthorized" in value ? TransactionError.unauthorized : "invalidAmount" in value ? TransactionError.invalidAmount : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _NotificationError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: NotificationError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_NotificationError_n27(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationNotFound: null;
} | {
    unauthorized: null;
}): NotificationError {
    return "notificationNotFound" in value ? NotificationError.notificationNotFound : "unauthorized" in value ? NotificationError.unauthorized : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    loanNotFound: null;
} | {
    alreadyApplied: null;
} | {
    unauthorized: null;
} | {
    invalidAmount: null;
}): LoanError {
    return "loanNotFound" in value ? LoanError.loanNotFound : "alreadyApplied" in value ? LoanError.alreadyApplied : "unauthorized" in value ? LoanError.unauthorized : "invalidAmount" in value ? LoanError.invalidAmount : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoanInfo>): Array<LoanInfo> {
    return value.map((x)=>from_candid_LoanInfo_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RepaymentScheduleEntry>): Array<RepaymentScheduleEntry> {
    return value.map((x)=>from_candid_RepaymentScheduleEntry_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
